# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cosmos_reasoning',
                'doc_host': 'https://HasanGoni.github.io',
                'git_url': 'https://github.com/HasanGoni/cosmos_reasoning',
                'lib_path': 'cosmos_reasoning'},
  'syms': {'cosmos_reasoning.core': {'cosmos_reasoning.core.foo': ('core.html#foo', 'cosmos_reasoning/core.py')}}}
